import {
	app,
	BrowserWindow,
	dialog,
	ipcMain,
	IpcMainInvokeEvent,
	protocol,
} from "electron";

import * as fs from "fs/promises";
import { glob } from "glob";

// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require("electron-squirrel-startup")) {
	app.quit();
}

let mainWindow: BrowserWindow;
const createWindow = (): void => {
	// Create the browser window.
	mainWindow = new BrowserWindow({
		height: 600,
		width: 800,
		webPreferences: {
			webSecurity: false,
			preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
			contextIsolation: true,
			nodeIntegration: true,
		},
	});

	mainWindow.removeMenu();

	// and load the index.html of the app.
	mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

	// Open the DevTools.
	mainWindow.webContents.openDevTools();
};

app.on("ready", () => {
	ipcMain.handle("openDirectory", openDirectory);
	ipcMain.handle("findSongs", findSongs);
	ipcMain.handle("saveSettings", saveSettings);
	ipcMain.handle("loadSettings", loadSettings);
	ipcMain.handle("saveLibrary", saveLibrary);
	ipcMain.handle("loadLibrary", loadLibrary);
	createWindow();
});

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on("window-all-closed", () => {
	if (process.platform !== "darwin") {
		app.quit();
	}
});

app.on("activate", () => {
	// On OS X it's common to re-create a window in the app when the
	// dock icon is clicked and there are no other windows open.
	if (BrowserWindow.getAllWindows().length === 0) {
		createWindow();
	}
});

protocol.registerSchemesAsPrivileged([
	{
		scheme: "file",
		privileges: {
			standard: true,
			bypassCSP: true,
			allowServiceWorkers: true,
			supportFetchAPI: true,
			corsEnabled: true,
			stream: true,
		},
	},
	{
		scheme: "https",
		privileges: {
			standard: true,
			bypassCSP: true,
			allowServiceWorkers: true,
			supportFetchAPI: true,
			corsEnabled: true,
			stream: true,
		},
	},
]);

async function openDirectory(
	_event: IpcMainInvokeEvent,
	defaultPath: string,
) {
	const { canceled, filePaths } = await dialog.showOpenDialog(mainWindow, {
		title: "select a directory",
		defaultPath: defaultPath,
		properties: ["openDirectory"],
	});
	if (!canceled) {
		return filePaths[0];
	}
}

async function findSongs(
	_event: IpcMainInvokeEvent,
	path: string,
) {
	return await glob(
		[
			"**/*.wav",
			"**/*.mp3",
			"**/*.flac",
			"**/*.ogg",
			"**/*.aac",
			"**/*.alac",
			"**/*.amr",
		],
		{
			cwd: path,
		},
	);
}

async function saveSettings(
	_event: IpcMainInvokeEvent,
	content: string,
) {
	return fs.writeFile("settings.json", content);
}

async function loadSettings() {
	return (await fs.readFile("settings.json").catch(() => Promise.resolve("")))
		.toString();
}

async function saveLibrary(
	_event: IpcMainInvokeEvent,
	path: string,
	content: string,
) {
	return fs.writeFile(`${path}/library.json`, content);
}

async function loadLibrary(
	_event: IpcMainInvokeEvent,
	path: string,
) {
	return (await fs.readFile(`${path}/library.json`).catch(() =>
		Promise.resolve("")
	)).toString();
}
