name: Create releases

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  release:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Detect package manager
        id: detect-package-manager
        run: |
          if [ -f "${{ github.workspace }}/yarn.lock" ]; then
            echo "manager=yarn" >> $GITHUB_OUTPUT
            echo "command=install" >> $GITHUB_OUTPUT
            echo "runner=yarn" >> $GITHUB_OUTPUT
            exit 0
          elif [ -f "${{ github.workspace }}/package.json" ]; then
            echo "manager=npm" >> $GITHUB_OUTPUT
            echo "command=ci" >> $GITHUB_OUTPUT
            echo "runner=npm" >> $GITHUB_OUTPUT
            exit 0
          else
            echo "Unable to determine package manager"
            exit 1
          fi
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: ${{ steps.detect-package-manager.outputs.manager }}
      - name: Install dependencies
        run: |
          ${{ steps.detect-package-manager.outputs.manager }} ${{ steps.detect-package-manager.outputs.command }}
          sudo dpkg --add-architecture i386
          sudo apt update
          sudo apt install -y wine wine64 mono-devel mono-runtime wine32:i386 # need these packages to build for windows
          cd /usr/bin
          sudo ln -s wine wine64 # electron forge looks for wine at wine64
      - name: Build for windows
        run: |
          ${{ steps.detect-package-manager.outputs.manager }} run make -- -p win32
          cd out/allium2-win32-x64
          zip -r allium2-windows.zip .
      - name: Build for linux
        run: |
          ${{ steps.detect-package-manager.outputs.manager }} run make -- -p linux
          cd out/allium2-linux-x64
          zip -r allium2-linux.zip .
      - name: Build for mac
        run: |
          ${{ steps.detect-package-manager.outputs.manager }} run make -- -p darwin
          cd out/allium2-darwin-x64
          zip -r allium2-mac.zip .
      - name: Get release metadata
        run: |
          echo "BODY=`git log | head -n 5 | tail -n 1`" >> "$GITHUB_ENV"
          echo "TAG=v`npm pkg get version | cut -d \\" -f 2`-release" >> "$GITHUB_ENV"
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ env.TAG }}
          body: ${{ env.BODY }}
          artifacts: "out/allium2-darwin-x64/allium2-mac.zip , out/allium2-linux-x64/allium2-linux.zip , out/allium2-win32-x64/allium2-windows.zip"
          generateReleaseNotes: true
          makeLatest: "latest"
